/**
 * Gateway dispatch event names (Discord-compatible).
 */
export const GatewayDispatchEvents = {
  Ready: 'READY',
  Resumed: 'RESUMED',
  MessageCreate: 'MESSAGE_CREATE',
  MessageUpdate: 'MESSAGE_UPDATE',
  MessageDelete: 'MESSAGE_DELETE',
  MessageDeleteBulk: 'MESSAGE_DELETE_BULK',
  MessageReactionAdd: 'MESSAGE_REACTION_ADD',
  MessageReactionRemove: 'MESSAGE_REACTION_REMOVE',
  MessageReactionRemoveAll: 'MESSAGE_REACTION_REMOVE_ALL',
  MessageReactionRemoveEmoji: 'MESSAGE_REACTION_REMOVE_EMOJI',
  InteractionCreate: 'INTERACTION_CREATE',
  GuildCreate: 'GUILD_CREATE',
  GuildUpdate: 'GUILD_UPDATE',
  GuildDelete: 'GUILD_DELETE',
  GuildBanAdd: 'GUILD_BAN_ADD',
  GuildBanRemove: 'GUILD_BAN_REMOVE',
  GuildEmojisUpdate: 'GUILD_EMOJIS_UPDATE',
  GuildStickersUpdate: 'GUILD_STICKERS_UPDATE',
  GuildIntegrationsUpdate: 'GUILD_INTEGRATIONS_UPDATE',
  GuildMemberAdd: 'GUILD_MEMBER_ADD',
  GuildMemberUpdate: 'GUILD_MEMBER_UPDATE',
  GuildMemberRemove: 'GUILD_MEMBER_REMOVE',
  GuildRoleCreate: 'GUILD_ROLE_CREATE',
  GuildRoleUpdate: 'GUILD_ROLE_UPDATE',
  GuildRoleDelete: 'GUILD_ROLE_DELETE',
  GuildScheduledEventCreate: 'GUILD_SCHEDULED_EVENT_CREATE',
  GuildScheduledEventUpdate: 'GUILD_SCHEDULED_EVENT_UPDATE',
  GuildScheduledEventDelete: 'GUILD_SCHEDULED_EVENT_DELETE',
  ChannelCreate: 'CHANNEL_CREATE',
  ChannelUpdate: 'CHANNEL_UPDATE',
  ChannelDelete: 'CHANNEL_DELETE',
  ChannelPinsUpdate: 'CHANNEL_PINS_UPDATE',
  InviteCreate: 'INVITE_CREATE',
  InviteDelete: 'INVITE_DELETE',
  TypingStart: 'TYPING_START',
  UserUpdate: 'USER_UPDATE',
  PresenceUpdate: 'PRESENCE_UPDATE',
  VoiceStateUpdate: 'VOICE_STATE_UPDATE',
  VoiceServerUpdate: 'VOICE_SERVER_UPDATE',
  WebhooksUpdate: 'WEBHOOKS_UPDATE',
} as const;

export type GatewayDispatchEventName =
  (typeof GatewayDispatchEvents)[keyof typeof GatewayDispatchEvents];
