export const Events = {
  Ready: 'ready',
  MessageCreate: 'messageCreate',
  MessageUpdate: 'messageUpdate',
  MessageDelete: 'messageDelete',
  MessageReactionAdd: 'messageReactionAdd',
  MessageReactionRemove: 'messageReactionRemove',
  MessageReactionRemoveAll: 'messageReactionRemoveAll',
  MessageReactionRemoveEmoji: 'messageReactionRemoveEmoji',
  InteractionCreate: 'interactionCreate',
  GuildCreate: 'guildCreate',
  GuildUpdate: 'guildUpdate',
  GuildDelete: 'guildDelete',
  ChannelCreate: 'channelCreate',
  ChannelUpdate: 'channelUpdate',
  ChannelDelete: 'channelDelete',
  GuildMemberAdd: 'guildMemberAdd',
  GuildMemberUpdate: 'guildMemberUpdate',
  GuildMemberRemove: 'guildMemberRemove',
  VoiceStateUpdate: 'voiceStateUpdate',
  VoiceServerUpdate: 'voiceServerUpdate',
  VoiceStatesSync: 'voiceStatesSync',
  Error: 'error',
  Debug: 'debug',
} as const;
